### ISSUE TITLE
No longer compatible with the latest version of Highcharts Version 11

### ISSUE THREAD

**Issue by rafaelrov** [blacklabel/grouped_categories#201] opened 2023-04-27 19:57 UTC

**Comment by dkoltg** [comment] 2023-04-28 15:11
I have the same issue. Is there planed to update the blacklabel library soon, so it works again with HC Version 11?

**Comment by raf18seb** [comment] 2023-05-24 13:47
Closing as a duplicate of https://github.com/blacklabel/grouped_categories/issues/201

**Closed by raf18seb** 2023-05-24 13:47 UTC
Labels: duplicate
