### ISSUE TITLE
Unable to align rotated labels or apply css elipse to text

### ISSUE THREAD

**Issue by MCSmit27** [blacklabel/grouped_categories#170] opened 2020-10-19 16:37 UTC
Hi,

Apologies for posting this as an Issue. I think it's rather a request for advise. I'm trying to achieve this or something similar (http://jsfiddle.net/mc_smit27/copg296e/5/) with the rotated labels. In one of my charts, I have very long names for the categories, and I can't seem to get the text to be cutoff with an ellipse value when overflowing the category area. I would also like to align the text to the bottom rather then anchor it to the middle. Is this at all possible? 

Unfortunately I don't have an online example of this, other then (https://stackblitz.com/edit/angular-ivy-cz2dhy) and I can't get the groupedOptions to work with Stackblitz although it works in my local project.

Attached is 2 examples of the issue I'm having. By setting the y:50, it works for some cases, and if the categories are small, the text is pushed back over the level 0 categories. In the other example it shows how most of the long category names overlap the chart region.

Any advise or help will be greatly appreciated.
![Example 2](https://user-images.githubusercontent.com/28202407/96480056-01a62180-123a-11eb-9963-2f2aad861af4.PNG)
![Example 1](https://user-images.githubusercontent.com/28202407/96480065-04087b80-123a-11eb-8fd2-fb8bc0dae413.PNG)

**Comment by pawelfus** [comment] 2020-10-21 14:22
Don't worry @MCSmit27 

To align labels to the bottom (which is left before rotation), set `labels.align` to "left" :) Then, to force ellipsis, set `labels.style.width` and `labels.style.textOverflow = "ellipsis"`. Then, in the last step, modify `labels.y` to translate labels. Demo: https://stackblitz.com/edit/angular-ivy-iptpxn

PS: The error in stackblitz was caused by TS: `xAxis.groupedOptions` is not part of the official Highcharts TS definitions. You need to add your own definition, or like in my demo, cast it.

**Comment by MCSmit27** [comment] 2020-10-22 07:12
Hi @pawelfus,

Yet again, thank you so much for the help. It's exactly what I was looking for!

**Comment by pawelfus** [comment] 2020-10-22 10:10
Great to hear that!
Closing the issue as resolved :)

**Closed by pawelfus** 2020-10-22 10:10 UTC
Labels: question
