### ISSUE TITLE
autoRotation property not working for groupedCatgeories with HC v8.1.2 and higher

### ISSUE THREAD

**Issue by praveenvitara** [blacklabel/grouped_categories#165] opened 2020-10-06 04:20 UTC
when using Highcharts 8.1.2 with latest grouped-categories.js module, the autoRotation functionality is not working.

Please find the sample chart reproducing the issue.

http://jsfiddle.net/praveenx9/yerkfs2p/

in the fiddle resize the chart container to see the autoRotation not working, while commenting the latest version and uncommenting the HC 6.2 version you can observe the autoRotation working while resizing the chart container.

**Comment by pawelfus** [comment] 2020-10-06 09:38
Thanks for reporting the issue. It's a duplicate of #137.

**Closed by pawelfus** 2020-10-06 09:38 UTC
